export const docs = [
  {
    _id: '5cd99d4bde30eff6ebccfbbe',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: '',
    spouse: 'Belemir',
    death: '',
    realm: '',
    hair: '',
    name: 'Adanel',
    wikiUrl: 'http://lotr.wikia.com//wiki/Adanel',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbbf',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Before ,TA 1944',
    spouse: '',
    death: 'Late ,Third Age',
    realm: '',
    hair: '',
    name: 'Adrahil I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Adrahil_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc0',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2917',
    spouse: 'Unnamed wife',
    death: 'TA 3010',
    realm: '',
    hair: '',
    name: 'Adrahil II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Adrahil_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc1',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: 'YT during the ,Noontide of Valinor',
    spouse: 'Loved ,Andreth but remained unmarried',
    death: 'FA 455',
    realm: '',
    hair: 'Golden',
    name: 'Aegnor',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aegnor',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc2',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: 'Mid ,First Age',
    spouse: 'Brodda',
    death: 'FA 495',
    realm: '',
    hair: '',
    name: 'Aerin',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aerin',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc3',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: 'Between ,SA 700, and ,SA 750',
    spouse: 'Orchaldor',
    death: 'Early ,Second Age',
    realm: '',
    hair: '',
    name: 'Ailinel',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ailinel',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc4',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2827',
    spouse: 'Unnamed wife',
    death: 'TA 2932',
    realm: '',
    hair: '',
    name: 'Aglahad',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aglahad',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc5',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Late ,First Age',
    spouse: 'None known',
    death: 'FA 489',
    realm: '',
    hair: '',
    name: 'Algund',
    wikiUrl: 'http://lotr.wikia.com//wiki/Algund',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc6',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: 'Between ,SA 700, and ,SA 750',
    spouse: '',
    death: 'Early ,Second Age',
    realm: '',
    hair: '',
    name: 'Almiel',
    wikiUrl: 'http://lotr.wikia.com//wiki/Almiel',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc7',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 3017',
    spouse: '',
    death: 'FO 95',
    realm: '',
    hair: '',
    name: 'Alphros',
    wikiUrl: 'http://lotr.wikia.com//wiki/Alphros',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc8',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: '',
    spouse: 'Tar-Meneldur',
    death: '',
    realm: 'Númenor',
    hair: '',
    name: 'Almarian',
    wikiUrl: 'http://lotr.wikia.com//wiki/Almarian',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbc9',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Late ,Second Age',
    spouse: 'Unnamed wife',
    death: 'Sailed West either SA 3310 fate unknown',
    realm: '',
    hair: '',
    name: 'Amandil',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amandil',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbca',
    height: '',
    race: 'Elf',
    gender: 'Female',
    birth: 'YT',
    spouse: 'Loved ,Finrod, but it is unknown whether they married',
    death: 'Still alive',
    realm: '',
    hair: '',
    name: 'Amarië',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amari%C3%AB',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbcb',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2544',
    spouse: 'Unnamed wife',
    death: 'TA 2645',
    realm: 'Rohan',
    hair: '',
    name: 'Aldor',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aldor',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbcc',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1330',
    spouse: 'Unnamed wife',
    death: 'TA 1540',
    realm: 'Gondor',
    hair: '',
    name: 'Aldamir',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aldamir',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbcd',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 726',
    spouse: 'Unnamed wife',
    death: 'TA 946',
    realm: 'Arthedain',
    hair: '',
    name: 'Amlaith',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amlaith',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbce',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: '',
    spouse: 'Nimrodel',
    death: 'TA 1981',
    realm: 'Lórien',
    hair: 'Golden',
    name: 'Amroth',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amroth',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbcf',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2994',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Amrothos',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amrothos',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd0',
    height: '',
    race: 'Elf',
    gender: 'Female',
    birth: 'YT',
    spouse: 'Fingolfin',
    death: '',
    realm: '',
    hair: '',
    name: 'Anairë',
    wikiUrl: 'http://lotr.wikia.com//wiki/Anair%C3%AB',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd1',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 136',
    spouse: 'Unnamed wife',
    death: 'TA 411',
    realm: 'Gondor',
    hair: '',
    name: 'Anardil',
    wikiUrl: 'http://lotr.wikia.com//wiki/Anardil',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd2',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Late ,Third Age',
    spouse: '',
    death: '',
    realm: '',
    hair: 'Dark',
    name: 'Anborn',
    wikiUrl: 'http://lotr.wikia.com//wiki/Anborn',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd3',
    height: '',
    race: 'Human',
    gender: 'Female',
    birth: 'FA 361',
    spouse: 'Loved ,Aegnor, but they never married',
    death: 'FA 455',
    realm: '',
    hair: 'Dark brown',
    name: 'Andreth',
    wikiUrl: 'http://lotr.wikia.com//wiki/Andreth',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd4',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'FA 440',
    spouse: 'Unnamed wife',
    death: 'FA 489',
    realm: '',
    hair: '',
    name: 'Andróg',
    wikiUrl: 'http://lotr.wikia.com//wiki/Andr%C3%B3g',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd5',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: 'Years of the Trees',
    spouse: 'None',
    death: 'FA 538',
    realm: 'Estolad',
    hair: 'Dark red',
    name: 'Amras',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amras',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd6',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Mid-,Third Age',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Angamaitë',
    wikiUrl: 'http://lotr.wikia.com//wiki/Angamait%C3%AB',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd7',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: 'Sometime during ,Years of the Trees, or the ,First Age',
    spouse: 'Unnamed wife',
    death: 'SA 3434',
    realm: 'Lórien',
    hair: '',
    name: 'Amdír',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amd%C3%ADr',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd8',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: 'Years of the Trees',
    spouse: 'None',
    death: 'YT 1497 ,Losgar',
    realm: '',
    hair: 'Dark red',
    name: 'Amrod',
    wikiUrl: 'http://lotr.wikia.com//wiki/Amrod',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbd9',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: '',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Annael',
    wikiUrl: 'http://lotr.wikia.com//wiki/Annael',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbda',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Late ,Third Age',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Angbor',
    wikiUrl: 'http://lotr.wikia.com//wiki/Angbor',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbdb',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2866',
    spouse: 'Unnamed wife',
    death: 'TA 2977',
    realm: '',
    hair: '',
    name: 'Angelimir',
    wikiUrl: 'http://lotr.wikia.com//wiki/Angelimir',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbdc',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: 'YT',
    spouse: 'Eldalótë',
    death: 'FA 455',
    realm: '',
    hair: 'Golden',
    name: 'Angrod',
    wikiUrl: 'http://lotr.wikia.com//wiki/Angrod',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbdd',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 3219',
    spouse: 'Unnamed wife',
    death: 'SA 3440',
    realm: 'Gondor',
    hair: '',
    name: 'Anárion',
    wikiUrl: 'http://lotr.wikia.com//wiki/An%C3%A1rion',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbde',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 2709',
    spouse: 'Unnamed wife',
    death: 'SA 2962',
    realm: 'Númenor',
    hair: '',
    name: 'Ar-Adûnakhôr',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ar-Ad%C3%BBnakh%C3%B4r',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbdf',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 2960',
    spouse: 'Inzilbêth',
    death: 'SA 3177',
    realm: 'Númenor',
    hair: '',
    name: 'Ar-Gimilzôr',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ar-Gimilz%C3%B4r',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe0',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 2798',
    spouse: 'Unnamed wife',
    death: 'SA 3033',
    realm: 'Númenor',
    hair: '',
    name: 'Ar-Zimrathôn',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ar-Zimrath%C3%B4n',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe1',
    height: 'Tall',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 3118',
    spouse: 'Tar-Míriel',
    death: 'Still alive',
    realm: 'Númenor',
    hair: '',
    name: 'Ar-Pharazôn',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ar-Pharaz%C3%B4n',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe2',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 2876',
    spouse: 'Unnamed wife',
    death: 'SA 3102',
    realm: 'Númenor',
    hair: '',
    name: 'Ar-Sakalthôr',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ar-Sakalth%C3%B4r',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe3',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2820',
    spouse: 'Unnamed wife',
    death: 'TA 2930',
    realm: '',
    hair: 'Dark, then grey (film)',
    name: 'Arador',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arador',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe4',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2296',
    spouse: 'Unnamed wife',
    death: 'TA 2455',
    realm: '',
    hair: '',
    name: 'Araglas',
    wikiUrl: 'http://lotr.wikia.com//wiki/Araglas',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe5',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2227',
    spouse: 'Unnamed wife',
    death: 'TA 2327',
    realm: '',
    hair: '',
    name: 'Aragorn I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aragorn_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe6',
    height: '198cm (6\'6")',
    race: 'Human',
    gender: 'Male',
    birth: 'March 1 ,2931',
    spouse: 'Arwen',
    death: 'FO 120',
    realm: 'Reunited Kingdom,Arnor,Gondor',
    hair: 'Dark',
    name: 'Aragorn II Elessar',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aragorn_II_Elessar',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe7',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2431',
    spouse: 'Unnamed wife',
    death: 'TA 2588',
    realm: '',
    hair: '',
    name: 'Aragost',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aragost',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe8',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2365',
    spouse: 'Unnamed wife',
    death: 'TA 2523',
    realm: '',
    hair: '',
    name: 'Arahad I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arahad_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbe9',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2563',
    spouse: 'Unnamed wife',
    death: 'TA 2719',
    realm: '',
    hair: '',
    name: 'Arahad II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arahad_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbea',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2012',
    spouse: 'Unnamed wife',
    death: 'TA 2177',
    realm: '',
    hair: '',
    name: 'Arahael',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arahael',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbeb',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1938',
    spouse: 'Unnamed wife',
    death: 'TA 2106',
    realm: '',
    hair: '',
    name: 'Aranarth',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aranarth',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbec',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 185',
    spouse: 'Unnamed wife',
    death: 'TA 435',
    realm: 'Arnor',
    hair: '',
    name: 'Arantar',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arantar',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbed',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2084',
    spouse: 'Unnamed wife',
    death: 'TA 2247',
    realm: '',
    hair: '',
    name: 'Aranuir',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aranuir',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbee',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: '',
    spouse: 'Unnamed wife',
    death: '',
    realm: '',
    hair: '',
    name: 'Aranwë',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aranw%C3%AB',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbef',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1789',
    spouse: 'Unnamed wife',
    death: 'TA 1964',
    realm: 'Arthedain',
    hair: '',
    name: 'Araphant',
    wikiUrl: 'http://lotr.wikia.com//wiki/Araphant',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf0',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2693',
    spouse: 'Unnamed wife',
    death: 'TA 2848',
    realm: '',
    hair: '',
    name: 'Arathorn I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arathorn_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf1',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2873',
    spouse: 'Gilraen',
    death: 'TA 2933',
    realm: '',
    hair: 'Dark (film)',
    name: 'Arathorn II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arathorn_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf2',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1711',
    spouse: 'Unnamed wife',
    death: 'TA 1891',
    realm: 'Arthedain,Arnor',
    hair: '',
    name: 'Araval',
    wikiUrl: 'http://lotr.wikia.com//wiki/Araval',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf3',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2156',
    spouse: 'Unnamed wife',
    death: 'TA 2319',
    realm: '',
    hair: '',
    name: 'Aravir',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aravir',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf4',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2497',
    spouse: 'Unnamed wife',
    death: 'TA 2654',
    realm: '',
    hair: '',
    name: 'Aravorn',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aravorn',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf5',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'After ,TA 1684',
    spouse: 'Unnamed wife',
    death: '',
    realm: '',
    hair: '',
    name: 'Arciryas',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arciryas',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf6',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2628',
    spouse: 'Unnamed wife',
    death: 'TA 2784',
    realm: '',
    hair: '',
    name: 'Arassuil',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arassuil',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf7',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1391',
    spouse: 'Unnamed wife',
    death: 'TA 1589',
    realm: 'Arthedain',
    hair: '',
    name: 'Araphor',
    wikiUrl: 'http://lotr.wikia.com//wiki/Araphor',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf8',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 3339',
    spouse: 'Unknown, possibly known',
    death: '',
    realm: 'TA 2',
    hair: '',
    name: 'Aratan',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aratan',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbf9',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 562',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Ardamir (son of Axantur)',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ardamir_(son_of_Axantur)',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbfa',
    height: 'Tall',
    race: 'Elf',
    gender: 'Female',
    birth: 'YT 1362',
    spouse: 'Eöl',
    death: 'FA 400',
    realm: '',
    hair: 'Dark',
    name: 'Aredhel',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aredhel',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbfb',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1226',
    spouse: 'Unnamed wife',
    death: 'TA 1356',
    realm: 'Arthedain,Arnor',
    hair: '',
    name: 'Argeleb I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Argeleb_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbfc',
    height: '',
    race: 'Elf',
    gender: 'Male',
    birth: '',
    spouse: '',
    death: '',
    realm: '',
    hair: '',
    name: 'Arminas',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arminas',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbfd',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'Late ,First Age',
    spouse: '',
    death: 'FA 460',
    realm: '',
    hair: '',
    name: 'Arthad',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arthad',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbfe',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1864',
    spouse: 'Fíriel',
    death: 'TA 1975',
    realm: 'Arthedain',
    hair: '',
    name: 'Arvedui',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arvedui',
  },
  {
    _id: '5cd99d4bde30eff6ebccfbff',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1553',
    spouse: 'Unnamed wife',
    death: 'TA 1743',
    realm: 'Arthedain,Arnor',
    hair: '',
    name: 'Arvegil',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arvegil',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc00',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1309',
    spouse: 'Unnamed wife',
    death: 'TA 1409',
    realm: 'Arnor,Arthedain',
    hair: '',
    name: 'Arveleg I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arveleg_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc01',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1633',
    spouse: 'Unnamed wife',
    death: 'TA 1813',
    realm: 'Arthedain,Arnor',
    hair: '',
    name: 'Arveleg II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arveleg_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc02',
    height: 'Tall',
    race: 'Elf',
    gender: 'Male',
    birth: 'Years of the Trees',
    spouse: 'None',
    death: 'YT 1500, or ,FA 1 ,Battle of the Lammoth',
    realm: '',
    hair: 'Possibly dark',
    name: 'Argon',
    wikiUrl: 'http://lotr.wikia.com//wiki/Argon',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc03',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 2757',
    spouse: 'Unnamed wife',
    death: 'TA 2912',
    realm: '',
    hair: '',
    name: 'Argonui',
    wikiUrl: 'http://lotr.wikia.com//wiki/Argonui',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc04',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 1473',
    spouse: 'Unnamed wife',
    death: 'TA 1670',
    realm: 'Arthedain',
    hair: '',
    name: 'Argeleb II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Argeleb_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc05',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 977',
    spouse: 'Unnamed wife',
    death: 'TA 1226',
    realm: 'Gondor',
    hair: '',
    name: 'Atanatar II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Atanatar_II',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc06',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'After ,SA 61',
    spouse: 'Possible unnamed wife',
    death: 'Early ,Second Age',
    realm: '',
    hair: '',
    name: 'Atanalcar',
    wikiUrl: 'http://lotr.wikia.com//wiki/Atanalcar',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc07',
    height: '',
    race: 'Elf',
    gender: 'Female',
    birth: 'TA 241',
    spouse: 'Aragorn II Elessar',
    death: 'FO 121',
    realm: 'Reunited Kingdom',
    hair: 'Black',
    name: 'Arwen',
    wikiUrl: 'http://lotr.wikia.com//wiki/Arwen',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc08',
    height: '',
    race: 'Dwarf',
    gender: 'Male',
    birth: 'FA 214',
    spouse: '',
    death: 'FA 473',
    realm: '',
    hair: '',
    name: 'Azaghâl',
    wikiUrl: 'http://lotr.wikia.com//wiki/Azagh%C3%A2l',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc09',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 213',
    spouse: 'Unnamed wife',
    death: 'Early ,Second Age',
    realm: '',
    hair: '',
    name: "Aulendil (Vardamir's son)",
    wikiUrl: 'http://lotr.wikia.com//wiki/Aulendil_(Vardamir%27s_son)',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0a',
    height: '',
    race: 'Hobbit',
    gender: 'Female',
    birth: 'TA 2981',
    spouse: '',
    death: 'Early-,Fourth Age',
    realm: '',
    hair: 'Blonde',
    name: 'Angelica Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Angelica_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0b',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'SA 395',
    spouse: 'Unnamed wife',
    death: '',
    realm: '',
    hair: '',
    name: 'Axantur',
    wikiUrl: 'http://lotr.wikia.com//wiki/Axantur',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0c',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2767',
    spouse: 'Berylla (Boffin) Baggins',
    death: 'TA 2858',
    realm: '',
    hair: '',
    name: 'Balbo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Balbo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0d',
    height: '',
    race: 'Human',
    gender: 'Male',
    birth: 'TA 480',
    spouse: 'Unnamed wife',
    death: 'TA 748',
    realm: 'Gondor',
    hair: '',
    name: 'Atanatar I',
    wikiUrl: 'http://lotr.wikia.com//wiki/Atanatar_I',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0e',
    height: '',
    race: 'Hobbit',
    gender: 'Female',
    birth: 'TA 2852',
    spouse: 'Bungo Baggins',
    death: 'TA 2934',
    realm: '',
    hair: 'Black',
    name: 'Belladonna (Took) Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Belladonna_(Took)_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc0f',
    height: '',
    race: 'Hobbit',
    gender: 'Female',
    birth: 'TA 2772',
    spouse: 'Balbo Baggins',
    death: 'TA 2871',
    realm: '',
    hair: '',
    name: 'Berylla (Boffin) Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Berylla_(Boffin)_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc10',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2846',
    spouse: '',
    death: 'TA 2926',
    realm: '',
    hair: '',
    name: 'Bungo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Bungo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc11',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2911',
    spouse: 'Unnamed wife',
    death: 'TA 3009',
    realm: '',
    hair: '',
    name: 'Dudo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Dudo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc12',
    height: '',
    race: 'Hobbit',
    gender: 'Female',
    birth: 'TA 2814',
    spouse: 'Mungo Baggins',
    death: 'TA 2916',
    realm: '',
    hair: '',
    name: 'Laura (Grubb) Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Laura_(Grubb)_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc13',
    height: '',
    race: 'Hobbit',
    gender: 'male',
    birth: 'TA 2864',
    spouse: 'Ruby Bolger',
    death: 'TA 2960',
    realm: '',
    hair: '',
    name: 'Fosco Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Fosco_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc14',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2908',
    spouse: 'Primula Brandybuck',
    death: 'TA 2980',
    realm: '',
    hair: '',
    name: 'Drogo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Drogo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc15',
    height: '1.06m (3\'6")',
    race: 'Hobbit',
    gender: 'Male',
    birth: '22 September ,TA 2968',
    spouse: '',
    death: 'Unknown (Last sighting ,September 29 ,3021,) (,SR 1421,)',
    realm: '',
    hair: 'Brown',
    name: 'Frodo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Frodo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc16',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2860',
    spouse: 'Camellia (Sackville) Baggins',
    death: 'TA 2950',
    realm: '',
    hair: '',
    name: 'Longo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Longo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc17',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2807',
    spouse: 'Laura Grubb',
    death: 'TA 2900',
    realm: '',
    hair: '',
    name: 'Mungo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Mungo_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc18',
    height: '',
    race: 'Hobbit',
    gender: 'Female',
    birth: 'TA 2950',
    spouse: 'Milo Burrows',
    death: '',
    realm: '',
    hair: '',
    name: 'Peony (Baggins) Burrows',
    wikiUrl: 'http://lotr.wikia.com//wiki/Peony_(Baggins)_Burrows',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc19',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2816',
    spouse: 'Mimosa Bunce',
    death: 'TA 2911',
    realm: '',
    hair: '',
    name: 'Ponto Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ponto_Baggins',
  },
  {
    _id: '5cd99d4bde30eff6ebccfc1a',
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2946',
    spouse: 'Unnamed wife',
    death: '',
    realm: '',
    hair: '',
    name: 'Ponto Baggins II',
    wikiUrl: 'http://lotr.wikia.com//wiki/Ponto_Baggins_II',
  },
];
